unique_name: dragon_1
display_name: Dragon
sprite_name: TrophyDragonQueen
description: Kill Moder over <color=orange>10</color> times
lore: The cries of the dragon queen brings relief to all who lived under her reign.
start_message: ''
stop_message: ''
tooltip: ''
defeat_key: defeated_dragon
achievement_type: CustomKills
goal: 10
duration: 0
start_effects:
- sfx_coins_placed
stop_effects: []
damage_modifiers:
- m_type: Blunt
  m_modifier: Normal
- m_type: Slash
  m_modifier: Normal
- m_type: Pierce
  m_modifier: Normal
- m_type: Chop
  m_modifier: Normal
- m_type: Pickaxe
  m_modifier: Normal
- m_type: Fire
  m_modifier: Normal
- m_type: Frost
  m_modifier: Resistant
- m_type: Lightning
  m_modifier: Normal
- m_type: Poison
  m_modifier: Normal
- m_type: Spirit
  m_modifier: Normal
modifiers:
  Attack: 1.1
  HealthRegen: 1.1
  StaminaRegen: 1
  RaiseSkills: 1.1
  Speed: 1
  Noise: 1
  MaxCarryWeight: 0
  Stealth: 1
  RunStaminaDrain: 1
  DamageReduction: 0
  FallDamage: 1
  EitrRegen: 1
