unique_name: hatchling_1
display_name: Glands
sprite_name: TrophyHatchling
description: Kill over <color=orange>100</color> Drakes
lore: Their is beauty in the joy of shooting down a drake from a high mountain top.
start_message: ''
stop_message: ''
tooltip: ''
defeat_key: defeated_leech
achievement_type: CustomKills
goal: 100
duration: 0
start_effects:
- sfx_coins_placed
stop_effects: []
damage_modifiers:
- m_type: Blunt
  m_modifier: Normal
- m_type: Slash
  m_modifier: Normal
- m_type: Pierce
  m_modifier: Normal
- m_type: Chop
  m_modifier: Normal
- m_type: Pickaxe
  m_modifier: Normal
- m_type: Fire
  m_modifier: Normal
- m_type: Frost
  m_modifier: Normal
- m_type: Lightning
  m_modifier: Normal
- m_type: Poison
  m_modifier: Normal
- m_type: Spirit
  m_modifier: Normal
modifiers:
  Attack: 1
  HealthRegen: 1
  StaminaRegen: 1.1
  RaiseSkills: 1
  Speed: 1
  Noise: 1
  MaxCarryWeight: 0
  Stealth: 1
  RunStaminaDrain: 1
  DamageReduction: 0
  FallDamage: 0.9
  EitrRegen: 1
