creature_prefab_name: Leech
bounty_name: Leech the Bloodsucker
sprite_name: TrophyLeech
biome: Swamp
reward_type: Item
item_reward:
  item_name: Bloodbag
  amount: 50
skill_reward:
  type: None
  amount: 0
experience_reward: 0
bounty_health: 60
damage_multiplier: 1.1
damages:
  blunt: 0
  slash: 0
  pierce: 10
  fire: 0
  frost: 0
  lightning: 0
  poison: 5
  spirit: 0
level: 2
defeat_key: defeated_leech
cost: 0
currency: Coins
