creature_prefab_name: Lox
bounty_name: Lox the Majestic
sprite_name: TrophyLox
biome: Plains
reward_type: Skill
item_reward:
  item_name: ''
  amount: 0
skill_reward:
  type: Axes
  amount: 10000
bounty_health: 1000
damage_multiplier: 1.5
damages:
  blunt: 30
  slash: 0
  pierce: 20
  fire: 0
  frost: 0
  lightning: 0
  poison: 0
  spirit: 0
level: 3
defeat_key: defeated_lox
