creature_prefab_name: SeekerBrute
bounty_name: Seeker the Dominator
sprite_name: TrophySeekerBrute
biome: Mountain
reward_type: Skill
item_reward:
  item_name: ''
  amount: 0
skill_reward:
  type: Polearms
  amount: 12000
bounty_health: 1500
damage_multiplier: 1.8
damages:
  blunt: 20
  slash: 0
  pierce: 40
  fire: 0
  frost: 0
  lightning: 0
  poison: 0
  spirit: 20
level: 3
defeat_key: defeated_seekerbrute
