creature_prefab_name: Skeleton_Poison
bounty_name: Skeleton the Corrupted
sprite_name: TrophySkeletonPoison
biome: Plains
reward_type: Skill
item_reward:
  item_name: ''
  amount: 0
skill_reward:
  type: Spears
  amount: 5000
bounty_health: 100
damage_multiplier: 1.2
damages:
  blunt: 0
  slash: 15
  pierce: 0
  fire: 0
  frost: 0
  lightning: 0
  poison: 10
  spirit: 0
level: 2
defeat_key: defeated_skeleton_poison
