creature_prefab_name: Ulv
bounty_name: Ulv the Wild
sprite_name: TrophyUlv
biome: Mountain
reward_type: Skill
item_reward:
  item_name: ''
  amount: 0
skill_reward:
  type: Polearms
  amount: 12000
bounty_health: 50
damage_multiplier: 1.1
damages:
  blunt: 0
  slash: 10
  pierce: 5
  fire: 0
  frost: 0
  lightning: 0
  poison: 0
  spirit: 0
level: 2
defeat_key: defeated_ulv
