m_prefab: Dandelion
m_alwaysSpawn: false
m_munin: true
m_priority: 0
m_key: DandelionKey
m_topic: DandelionAreUseless
m_label: DandelionInfo
m_text: Dandelions are found all around the meadows. They can aid in progressing through this world, but really are mostly useless.
