Name: Potion_Stoneskin_TW
Status_m_name: $potion_stoneskin_TW
Category: buffpotion
IconName: PotionStoneskin_TW
ClonedSE: 
CustomIcon: 
FlashIcon: false
CooldownIcon: true
Tooltip: $SE_potion_stoneskin_description_TW
Attributes: None
StartMessageLoc: TopLeft
StartMessage: $se_potion_start
StopMessageLoc: TopLeft
StopMessage: ''
RepeatMessageLoc: TopLeft
RepeatMessage: ''
RepeatInterval: 0
TimeToLive: 30
StartEffect_: 
StopEffect_: 
StartEffect_PLUS:
- name: vfx_Potion_stoneskin_TW
  m_enabled: true
  m_variant: -1
  m_attach: true
  m_follow: false
  m_inheritParentRotation: false
  m_inheritParentScale: false
  m_multiplyParentVisualScale: false
  m_randomRotation: false
  m_scale: true
  m_childTransform: ''
- name: sfx_Potion_eitr_minor_TW
  m_enabled: true
  m_variant: -1
  m_attach: true
  m_follow: false
  m_inheritParentRotation: false
  m_inheritParentScale: false
  m_multiplyParentVisualScale: false
  m_randomRotation: false
  m_scale: false
  m_childTransform: ''
StopEffect_PLUS: []
Cooldown: 0
ActivationAnimation: gpower
SeData:
  m_tickInterval: 0
  m_healthPerTickMinHealthPercentage: 0
  m_healthPerTick: 0
  m_healthOverTime: 0
  m_healthOverTimeDuration: 0
  m_healthOverTimeInterval: 0
  m_staminaOverTime: 0
  m_staminaOverTimeDuration: 0
  m_staminaDrainPerSec: 0
  m_runStaminaDrainModifier: 0
  m_jumpStaminaUseModifier: 0
  m_eitrOverTime: 0
  m_eitrOverTimeDuration: 0
  m_healthRegenMultiplier: 1
  m_staminaRegenMultiplier: 1
  m_eitrRegenMultiplier: 1
  m_raiseSkill: None
  m_raiseSkillModifier: 0
  m_skillLevel: None
  m_skillLevelModifier: 0
  m_skillLevel2: None
  m_skillLevelModifier2: 0
  m_mods:
  - m_type: Blunt
    m_modifier: Resistant
  - m_type: Slash
    m_modifier: Resistant
  - m_type: Pierce
    m_modifier: Resistant
  m_modifyAttackSkill: None
  m_damageModifier: 0
  m_noiseModifier: 0
  m_stealthModifier: 0
  m_addMaxCarryWeight: 0
  m_speedModifier: -0.8
  m_jumpModifier:
    x: -0.8
    y: -0.8
    z: -0.8
    normalized: &o0
      x: -0.5773503
      y: -0.5773503
      z: -0.5773503
      normalized: *o0
      magnitude: 1
      sqrMagnitude: 0.9999999
    magnitude: 1.385641
    sqrMagnitude: 1.92
  m_maxMaxFallSpeed: 0
  m_fallDamageModifier: 0
  m_tickTimer: 0
  m_healthOverTimeTimer: 0
  m_healthOverTimeTicks: 0
  m_healthOverTimeTickHP: 0
SeShield: 
