- prefab: BGP_Pickable_SilicaOre
  enabled: true
  max: 20
  biome: Swamp, Mountain, BlackForest, Plains
  maxAltitude: 1000
  maxTerrainDelta: 2
  groupSizeMin: 2
  groupSizeMax: 4
  groupRadius: 48
- prefab: BGP_SilicaVein
  enabled: true
  max: 2
  chanceToUseGroundTilt: 1
  biome: Plains
  minAltitude: -0.5
  maxAltitude: 1000
  maxTerrainDelta: 2
  groupRadius: 80
