- prefab: WaypointLocation
  enabled: true
  quantity: 200
  maxDistance: 1
  minAltitude: 0
  group: Waypoints
  minDistanceFromSimilar: 1000
  maxTerrainDelta: 100
  exteriorRadius: 5.3
  clearArea: true
  noBuild: true
  surroundCheckVegetation: true
  surroundCheckDistance: 10
