- prefab: BCA_Wild_Tomato
  enabled: true
  max: 2
  biome: Meadows, BlackForest, Plains
  biomeArea: edge
  maxAltitude: 1000
  maxTerrainDelta: 2
  groupSizeMax: 3
  groupRadius: 32
- prefab: BCA_Wild_ChiliPepper
  enabled: true
  max: 2
  biome: Meadows, BlackForest, Plains
  biomeArea: median
  maxAltitude: 1000
  maxTerrainDelta: 2
  groupSizeMax: 3
  groupRadius: 32
- prefab: BCA_MineRock_Salt
  enabled: true
  min: 8
  max: 10
  scaleMin: 0.8
  chanceToUseGroundTilt: 1
  biomeArea: edge
  minAltitude: -0.2
  maxAltitude: 1.5
  maxTerrainDelta: 2
  groundOffset: -0.5
