- prefab: Meadows3_RtD
  amount: 4
  biome: Mistlands
  instanced: true
  scaleMin: 2
  scaleMax: 2.2
  maxTilt: 30
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: Mistlands1_RtD
  amount: 5
  biome: Mistlands
  instanced: true
  scaleMax: 1.2
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: Mistlands2_RtD
  amount: 5
  biome: Mistlands
  instanced: true
  scaleMin: 2
  scaleMax: 3.2
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: Mistlands3_RtD
  amount: 5
  biome: Mistlands
  instanced: true
  scaleMin: 2
  scaleMax: 3.2
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: MistlandsGrass1_RtD
  enabled: false
  amount: 2
  biome: Mistlands
  instanced: true
  scaleMax: 1.2
  maxTilt: 0
  minAltitude: 1
  maxAltitude: 500
  snapToWater: true
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: MistlandsGrass2_RtD
  enabled: false
  amount: 2
  biome: Mistlands
  instanced: true
  scaleMax: 1.2
  maxTilt: 0
  minAltitude: 0
  maxAltitude: 500
  snapToWater: true
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: MistlandsGrass3_RtD
  enabled: false
  amount: 2
  biome: Mistlands
  instanced: true
  scaleMax: 1.2
  maxTilt: 0
  minAltitude: 1
  maxAltitude: 500
  snapToWater: true
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: MistlandsGrass4_RtD
  enabled: false
  amount: 2
  biome: Mistlands
  instanced: true
  scaleMax: 1.2
  maxTilt: 0
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  minOceanDepth: 1
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: DesertGrass1_RtD
  amount: 2
  biome: AshLands
  instanced: true
  maxTilt: 80
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: DesertGrass2_RtD
  amount: 2
  biome: AshLands
  instanced: true
  maxTilt: 80
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: DesertGrass3_RtD
  amount: 2
  biome: AshLands
  instanced: true
  maxTilt: 80
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: DesertGrass4_RtD
  amount: 2
  biome: AshLands
  instanced: true
  maxTilt: 80
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: DesertGrass5_RtD
  amount: 2
  biome: AshLands
  instanced: true
  maxTilt: 80
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: DesertGrass6_RtD
  amount: 2
  biome: AshLands
  instanced: true
  maxTilt: 80
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: NorthGrass1_RtD
  amount: 3
  biome: DeepNorth
  instanced: true
  scaleMax: 1.2
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: NorthGrass2_RtD
  amount: 3
  biome: DeepNorth
  instanced: true
  scaleMax: 1.2
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: Meadows1_RtD
  amount: 1
  biome: Meadows
  instanced: true
  scaleMax: 1.2
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: Meadows2_RtD
  amount: 1
  biome: Meadows
  instanced: true
  scaleMax: 1.2
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: WormWood_RtD
  amount: 3
  biome: Meadows
  instanced: true
  scaleMax: 1.2
  maxTilt: 3
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  fractalThresholdMin: 0.5
- prefab: MeadowsGrass1_RtD
  amount: 3
  biome: Meadows
  instanced: true
  scaleMax: 1.2
  maxTilt: 1
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  fractalThresholdMin: 0.5
- prefab: MeadowsGrass2_RtD
  amount: 3
  biome: Meadows
  instanced: true
  scaleMax: 1.2
  maxTilt: 1
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  fractalThresholdMin: 0.5
- prefab: MeadowsGrass3_RtD
  amount: 4
  biome: Meadows
  instanced: true
  scaleMax: 1.2
  maxTilt: 1
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  fractalThresholdMin: 0.5
- prefab: MeadowsWeed1_RtD
  amount: 4
  biome: Meadows
  instanced: true
  scaleMax: 1.2
  maxTilt: 1
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  fractalThresholdMin: 0.5
- prefab: MeadowsClutter2_RtD
  amount: 1
  biome: Meadows
  instanced: true
  scaleMax: 1.2
  maxTilt: 50
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  fractalThresholdMin: 0.5
- prefab: MeadowsClutter3_RtD
  amount: 1
  biome: Meadows
  instanced: true
  scaleMax: 1.2
  maxTilt: 50
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  fractalThresholdMin: 0.5
- prefab: BlackForest1_RtD
  amount: 5
  biome: BlackForest
  instanced: true
  scaleMin: 2
  scaleMax: 2.6
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: BlackForest2_RtD
  amount: 5
  biome: BlackForest
  instanced: true
  scaleMin: 2
  scaleMax: 2.6
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: GreenGrass1_RtD
  enabled: false
  amount: 35
  biome: BlackForest
  instanced: true
  scaleMax: 1.2
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  fractalThresholdMin: 0.5
- prefab: MeadowsClutter1_RtD
  amount: 1
  biome: Swamp
  instanced: true
  scaleMax: 1.2
  maxTilt: 5
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  fractalThresholdMin: 0.5
- prefab: Swamps1_RtD
  amount: 5
  biome: Swamp
  instanced: true
  scaleMax: 1.2
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: Swamps2_RtD
  amount: 5
  biome: Swamp
  instanced: true
  scaleMax: 1.2
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: Swamps3_RtD
  amount: 5
  biome: Swamp
  instanced: true
  scaleMax: 1.2
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: SwampGrass1_RtD
  amount: 3
  biome: Swamp
  instanced: true
  scaleMax: 1.2
  maxTilt: 30
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  fractalThresholdMin: 0.5
- prefab: SwampGrass2_RtD
  amount: 3
  biome: Swamp
  instanced: true
  scaleMax: 1.2
  maxTilt: 30
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  fractalThresholdMin: 0.5
- prefab: SwampGrass3_RtD
  amount: 3
  biome: Swamp
  instanced: true
  scaleMax: 1.2
  maxTilt: 30
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  fractalThresholdMin: 0.5
- prefab: SwampGrass4_RtD
  amount: 3
  biome: Swamp
  instanced: true
  scaleMax: 1.2
  maxTilt: 30
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  fractalThresholdMin: 0.5
- prefab: SwampPlant_RtD
  amount: 3
  biome: Swamp
  instanced: true
  scaleMax: 1.2
  maxTilt: 5
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  fractalThresholdMin: 0.5
- prefab: ForestBush1_RtD
  amount: 3
  biome: Swamp
  instanced: true
  scaleMax: 1.2
  maxTilt: 5
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  fractalThresholdMin: 0.5
- prefab: ForestBush2_RtD
  amount: 3
  biome: Swamp
  instanced: true
  scaleMax: 1.2
  maxTilt: 5
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  fractalThresholdMin: 0.5
- prefab: Daisy_RtD
  amount: 5
  biome: Plains
  instanced: true
  scaleMin: 1.5
  scaleMax: 2.2
  maxTilt: 30
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  fractalThresholdMin: 0.5
- prefab: PlainsGrass1_RtD
  amount: 5
  biome: Plains
  instanced: true
  scaleMin: 1.5
  scaleMax: 2.2
  maxTilt: 30
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  fractalThresholdMin: 0.5
- prefab: PlainsGrass2_RtD
  amount: 5
  biome: Plains
  instanced: true
  scaleMax: 1.2
  maxTilt: 30
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  fractalThresholdMin: 0.5
- prefab: PlainsGrass3_RtD
  amount: 5
  biome: Plains
  instanced: true
  scaleMax: 1.2
  maxTilt: 30
  minAltitude: 1
  maxAltitude: 500
  terrainTilt: true
  fractalThresholdMin: 0.5
