- prefab: LoreStoneOdin_Ashlands_TW
  biome: AshLands
  biomeArea: median
  quantity: 3
  minDistance: 0.8
  maxDistance: 1.05
  minAltitude: 5
  prioritized: true
  group: StatueOdin
  minDistanceFromSimilar: 4000
  slopeRotation: true
  maxTerrainDelta: 100
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 8
  clearArea: true
- prefab: StatueAshlands_TW
  biome: AshLands
  quantity: 3
  minDistance: 0.8
  maxDistance: 1.05
  minAltitude: 5
  prioritized: true
  group: StatueAshlands
  minDistanceFromSimilar: 3000
  slopeRotation: true
  maxTerrainDelta: 100
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 8
  clearArea: true
- prefab: AltarSythrak_TW
  biome: AshLands
  biomeArea: median
  quantity: 3
  maxDistance: 1
  minAltitude: 90
  prioritized: true
  group: altardragonashlands
  minDistanceFromSimilar: 3000
  discoverLabel: $sythrak_discover_TW
  randomRotation: true
  maxTerrainDelta: 15
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 63
  clearArea: true
  noBuild: true
- prefab: Vegvisir_location_Sythrak_TW
  biome: AshLands
  biomeArea: edge
  quantity: 4
  maxDistance: 1
  minAltitude: 30
  maxAltitude: 80
  prioritized: true
  group: vegvisirashlands
  minDistanceFromSimilar: 4000
  randomRotation: true
  maxTerrainDelta: 5
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 5
  clearArea: true
- prefab: Vegvisir_location_AshlandsStones_TW
  biome: AshLands
  quantity: 4
  maxDistance: 1
  minAltitude: 30
  maxAltitude: 80
  prioritized: true
  group: vegvisirashlands
  minDistanceFromSimilar: 3000
  randomRotation: true
  maxTerrainDelta: 5
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 3
  clearArea: true
- prefab: Ashlands_Flamehole_TW
  biome: AshLands
  quantity: 50
  maxDistance: 1
  minAltitude: 65
  maxAltitude: 95
  prioritized: true
  group: ashlandsflamehole
  minDistanceFromSimilar: 250
  randomRotation: true
  maxTerrainDelta: 2
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 5
  clearArea: true
- prefab: AshlandsNest_TW
  biome: AshLands
  quantity: 15
  minDistance: 0.8
  maxDistance: 1.05
  minAltitude: 75
  prioritized: true
  group: firedrakenest
  minDistanceFromSimilar: 300
  slopeRotation: true
  maxTerrainDelta: 100
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 5
  clearArea: true
- prefab: Ashlands_BossStones_TW
  biome: AshLands
  biomeArea: median
  quantity: 1
  maxDistance: 1
  minAltitude: 40
  prioritized: true
  group: bossstonesashlands
  minDistanceFromSimilar: 4000
  randomRotation: true
  maxTerrainDelta: 8
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 16
  clearArea: true
  noBuild: true
- prefab: AshlandsMountain1_TW
  biome: AshLands
  quantity: 10
  maxDistance: 1
  minAltitude: 60
  maxAltitude: 90
  prioritized: true
  centerFirst: true
  group: ashlandsmountain
  minDistanceFromSimilar: 2000
  randomRotation: true
  maxTerrainDelta: 8
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 99
  clearArea: true
  noBuild: true
