- prefab: LoreStoneThor_DeepNorth_TW
  biome: DeepNorth
  biomeArea: median
  quantity: 3
  minDistance: 0.8
  maxDistance: 1.05
  minAltitude: 5
  prioritized: true
  group: StatueThor
  minDistanceFromSimilar: 4000
  slopeRotation: true
  maxTerrainDelta: 100
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 8
  clearArea: true
- prefab: Vegvisir_location_DeepNorthStones_TW
  biome: DeepNorth
  quantity: 4
  maxDistance: 1
  minAltitude: 30
  maxAltitude: 80
  prioritized: true
  group: vegvisirdeepnorth
  minDistanceFromSimilar: 3000
  randomRotation: true
  maxTerrainDelta: 5
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 5
  clearArea: true
- prefab: StatueDeepNorth_TW
  biome: DeepNorth
  quantity: 3
  minDistance: 0.8
  maxDistance: 1.05
  minAltitude: 5
  prioritized: true
  group: StatueDeepNorth
  minDistanceFromSimilar: 3000
  slopeRotation: true
  maxTerrainDelta: 100
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 8
  clearArea: true
- prefab: DeepNorth_BossStones_TW
  biome: DeepNorth
  biomeArea: median
  quantity: 1
  maxDistance: 1
  minAltitude: 40
  prioritized: true
  group: bossstonesdeepnorth
  minDistanceFromSimilar: 4000
  randomRotation: true
  maxTerrainDelta: 8
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 12
  clearArea: true
  noBuild: true
- prefab: AltarStormHerald_TW
  biome: DeepNorth
  biomeArea: median
  quantity: 3
  maxDistance: 1
  minAltitude: 65
  prioritized: true
  group: stormheraldaltar
  minDistanceFromSimilar: 1500
  discoverLabel: $stormtemple_discover_TW
  maxTerrainDelta: 35
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 110
  clearArea: true
  noBuild: true
- prefab: CaveDeepNorth_TW
  biome: DeepNorth
  biomeArea: median
  quantity: 8
  maxDistance: 1
  minAltitude: 25
  maxAltitude: 60
  prioritized: true
  group: jotunn
  minDistanceFromSimilar: 1000
  maxTerrainDelta: 5
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 12
  clearArea: true
- prefab: DeepNorthJotunnCamp_TW
  biome: DeepNorth
  biomeArea: median
  quantity: 5
  maxDistance: 1
  minAltitude: 15
  maxAltitude: 70
  prioritized: true
  group: jotunn
  minDistanceFromSimilar: 1500
  maxTerrainDelta: 25
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 30
  clearArea: true
  randomDamage: true
- prefab: Vegvisir_location_StormHerald_TW
  biome: DeepNorth
  biomeArea: edge
  quantity: 4
  maxDistance: 1
  minAltitude: 25
  maxAltitude: 80
  prioritized: true
  group: vegvisirstormherald
  minDistanceFromSimilar: 4000
  randomRotation: true
  maxTerrainDelta: 3
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 8
  clearArea: true
- prefab: DeepNorth_MammothSkull_TW
  biome: DeepNorth
  quantity: 25
  maxDistance: 1
  minAltitude: 35
  maxAltitude: 95
  prioritized: true
  group: deepnorthmammothskull
  minDistanceFromSimilar: 350
  randomRotation: true
  maxTerrainDelta: 2
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 5
  clearArea: true
- prefab: DeepNorthNest_TW
  biome: DeepNorth
  quantity: 15
  minDistance: 0.8
  maxDistance: 1.05
  minAltitude: 85
  prioritized: true
  group: stormheraldaltar
  minDistanceFromSimilar: 300
  slopeRotation: true
  maxTerrainDelta: 100
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 5
  clearArea: true
