- prefab: Pickable_VolcanicStone_TW
  enabled: true
  min: 3
  max: 3
  forcePlacement: true
  chanceToUseGroundTilt: 1
  biome: AshLands
  minAltitude: 0.1
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groupSizeMax: 3
  groupRadius: 5
- prefab: Pickable_GlacierStone_TW
  enabled: true
  min: 3
  max: 3
  forcePlacement: true
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.1
  maxAltitude: 1000
  maxTerrainDelta: 2
  groupSizeMax: 3
  groupRadius: 5
- prefab: MineRock_Tyranium_TW
  enabled: true
  min: 0.5
  max: 0.7
  scaleMax: 1.1
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.1
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -0.5
  inForest: true
  forestTresholdMin: 0.5
- prefab: MineRock_VolcanicFragment_TW
  enabled: true
  max: 0.4
  scaleMax: 1.1
  biome: AshLands
  minAltitude: 0.1
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -1
  inForest: true
  forestTresholdMin: 0.5
- prefab: Rock_Ashlands_TW
  enabled: true
  max: 10
  scaleMin: 0.9
  scaleMax: 1.1
  chanceToUseGroundTilt: 1
  biome: AshLands
  minAltitude: 0.01
  maxAltitude: 1000
  maxTerrainDelta: 4
- prefab: Boulder_DeepNorth_TW
  enabled: true
  max: 0.5
  scaleMin: 0.8
  scaleMax: 1.2
  randTilt: 10
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.01
  maxAltitude: 1000
  maxTerrainDelta: 2
  groundOffset: -2
- prefab: SmallRock_Ashlands_TW
  enabled: true
  max: 0.6
  scaleMin: 0.9
  scaleMax: 1.2
  chanceToUseGroundTilt: 1
  biome: AshLands
  minAltitude: 0.01
  maxAltitude: 1000
  maxTerrainDelta: 2
  groupSizeMax: 2
  groupRadius: 10
- prefab: MineRock_GlacierFragment_TW
  enabled: true
  max: 0.6
  scaleMax: 1.1
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.1
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -1
  inForest: true
  forestTresholdMin: 0.5
- prefab: BurnedTree_TW
  enabled: true
  min: 3
  max: 3
  scaleMin: 0.8
  scaleMax: 1.4
  randTilt: 4
  chanceToUseGroundTilt: 0.05
  biome: AshLands
  minAltitude: 5
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -1
  groupSizeMax: 3
  groupRadius: 32
  forestTresholdMin: 1.05
  forestTresholdMax: 1.3
- prefab: DeadBurnedTree_TW
  enabled: true
  min: 30
  max: 30
  scaleMin: 0.8
  scaleMax: 1.2
  randTilt: 4
  chanceToUseGroundTilt: 0.05
  biome: AshLands
  minAltitude: 5
  maxAltitude: 1000
  maxTilt: 30
  maxTerrainDelta: 2
  groundOffset: -1
  groupSizeMax: 3
  groupRadius: 32
  forestTresholdMin: 1.05
  forestTresholdMax: 1.3
- prefab: Stalag_DeepNorth_TW
  enabled: true
  max: 0.6
  scaleMax: 1.1
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.1
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -1
  inForest: true
  forestTresholdMin: 0.5
- prefab: BlackIce_DeepNorth_TW
  enabled: true
  max: 0.4
  scaleMax: 1.1
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.1
  maxAltitude: 45
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -0.5
  groupSizeMax: 2
  groupRadius: 32
  inForest: true
  forestTresholdMin: 0.5
- prefab: BorealTree_TW
  enabled: true
  min: 10
  max: 10
  scaleMin: 0.8
  scaleMax: 1.4
  randTilt: 4
  chanceToUseGroundTilt: 0.5
  biome: DeepNorth
  minAltitude: 5
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -1
  groupSizeMax: 5
  groupRadius: 32
  forestTresholdMin: 1.05
  forestTresholdMax: 1.3
- prefab: DeadBorealTree_TW
  enabled: true
  min: 32
  max: 36
  scaleMin: 0.8
  scaleMax: 1.2
  randTilt: 4
  chanceToUseGroundTilt: 0.5
  biome: DeepNorth
  minAltitude: 5
  maxAltitude: 1000
  maxTilt: 30
  maxTerrainDelta: 2
  groundOffset: -1
  groupSizeMax: 3
  groupRadius: 32
  forestTresholdMin: 1.05
  forestTresholdMax: 1.3
- prefab: Pickable_TundraBerryBush_TW
  enabled: true
  max: 0.8
  chanceToUseGroundTilt: 0.05
  biome: DeepNorth
  minAltitude: 10
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groupSizeMax: 2
  groupRadius: 32
- prefab: Pickable_PrimalLeak_TW
  enabled: true
  max: 0.65
  chanceToUseGroundTilt: 0.05
  biome: DeepNorth
  minAltitude: 10
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -0.2
  groupSizeMax: 2
  groupRadius: 16
- prefab: Pickable_AshenRoot_TW
  enabled: true
  max: 0.5
  biome: AshLands
  minAltitude: 10
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -0.25
  groupSizeMax: 2
  groupRadius: 16
- prefab: Pickable_FireLilly_TW
  enabled: true
  max: 0.5
  biome: AshLands
  minAltitude: 10
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groupSizeMax: 2
  groupRadius: 32
- prefab: DeadBorealPineTree_TW
  enabled: true
  min: 4
  max: 10
  scaleMin: 0.4
  scaleMax: 0.8
  randTilt: 4
  chanceToUseGroundTilt: 0.5
  biome: DeepNorth
  minAltitude: 5
  maxAltitude: 1000
  maxTilt: 8
  maxTerrainDelta: 2
  groundOffset: -1
  groupSizeMax: 3
  groupRadius: 32
  forestTresholdMin: 1.02
  forestTresholdMax: 1.6
- prefab: BorealPineTree_TW
  enabled: true
  min: 3
  max: 7
  scaleMin: 0.42
  scaleMax: 0.8
  randTilt: 4
  chanceToUseGroundTilt: 0.5
  biome: DeepNorth
  minAltitude: 5
  maxAltitude: 1000
  maxTilt: 8
  maxTerrainDelta: 2
  groundOffset: -1
  groupSizeMax: 3
  groupRadius: 32
  forestTresholdMin: 1.02
  forestTresholdMax: 1.6
- prefab: BorealPineTreeNormal_TW
  enabled: true
  min: 5
  max: 8
  scaleMin: 0.42
  scaleMax: 0.7
  randTilt: 4
  chanceToUseGroundTilt: 0.5
  biome: DeepNorth
  minAltitude: 5
  maxAltitude: 1000
  maxTilt: 8
  maxTerrainDelta: 2
  groundOffset: -1
  groupSizeMax: 3
  groupRadius: 32
  forestTresholdMin: 1.02
  forestTresholdMax: 1.6
- prefab: GswordAL_TW
  enabled: true
  max: 0.2
  scaleMin: 0.8
  scaleMax: 1.1
  biome: AshLands
  biomeArea: median
  minAltitude: 20
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 3
  forestTresholdMin: 0.5
- prefab: GswordDN_TW
  enabled: true
  max: 0.2
  scaleMin: 0.8
  scaleMax: 1.1
  biome: DeepNorth
  biomeArea: median
  minAltitude: 20
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 3
  groundOffset: 1
  inForest: true
  forestTresholdMin: 0.5
- prefab: Rock_DeepNorth_TW
  enabled: true
  max: 10
  scaleMax: 1.4
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.01
  maxAltitude: 1000
  maxTerrainDelta: 4
  groundOffset: -0.1
- prefab: RockPillar_Ashlands_TW
  enabled: true
  max: 0.25
  scaleMin: 0.8
  scaleMax: 1.3
  randTilt: 20
  chanceToUseGroundTilt: 0.05
  biome: AshLands
  minAltitude: -1
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -3
  inForest: true
  forestTresholdMin: 1
  forestTresholdMax: 1.2
- prefab: RockChunk_DeepNorth_TW
  enabled: true
  max: 0.5
  scaleMin: 0.8
  scaleMax: 1.1
  randTilt: 20
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.01
  maxAltitude: 1000
  maxTerrainDelta: 2
  groundOffset: -1
- prefab: Pickable_BranchBoreal_TW
  enabled: true
  max: 1
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.01
  maxAltitude: 1000
  maxTerrainDelta: 2
- prefab: BorealBush1_TW
  enabled: true
  min: 3
  max: 3
  forcePlacement: true
  scaleMin: 0.7
  scaleMax: 1.2
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.1
  maxAltitude: 1000
  maxTilt: 15
  maxTerrainDelta: 2
  groupSizeMax: 4
  groupRadius: 25
- prefab: BorealBush2_TW
  enabled: true
  min: 3
  max: 3
  forcePlacement: true
  scaleMin: 0.7
  scaleMax: 1.2
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.1
  maxAltitude: 1000
  maxTilt: 15
  maxTerrainDelta: 2
  groupSizeMax: 4
  groupRadius: 20
- prefab: BorealBush3_TW
  enabled: true
  min: 2
  max: 2
  forcePlacement: true
  scaleMin: 0.7
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.1
  maxAltitude: 1000
  maxTilt: 15
  maxTerrainDelta: 2
  groupRadius: 32
- prefab: Pickable_BranchScorched_TW
  enabled: true
  max: 1
  chanceToUseGroundTilt: 1
  biome: AshLands
  minAltitude: 0.01
  maxAltitude: 1000
  maxTerrainDelta: 2
  inForest: true
- prefab: Boulder_Ashlands_TW
  enabled: true
  max: 0.5
  scaleMin: 0.8
  scaleMax: 1.2
  randTilt: 10
  chanceToUseGroundTilt: 1
  biome: AshLands
  minAltitude: 0.01
  maxAltitude: 1000
  maxTerrainDelta: 2
  groundOffset: -2
- prefab: RockPillar_DeepNorth_TW
  enabled: true
  max: 0.3
  scaleMin: 0.8
  scaleMax: 1.3
  randTilt: 20
  chanceToUseGroundTilt: 0.05
  biome: DeepNorth
  minAltitude: -1
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -2.5
  forestTresholdMin: 1
  forestTresholdMax: 1.2
- prefab: Pickable_Mushroom_Wintercap_TW
  enabled: true
  max: 0.7
  randTilt: 10
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.01
  maxAltitude: 60
  maxTerrainDelta: 2
  groupRadius: 32
- prefab: AshenTree_TW
  enabled: true
  max: 0.4
  scaleMin: 0.8
  scaleMax: 1.2
  randTilt: 1
  biome: AshLands
  minAltitude: 5
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 3
  groundOffset: -0.5
  forestTresholdMin: 0.5
- prefab: Pickable_Mushroom_Flamecap_TW
  enabled: true
  max: 0.7
  randTilt: 5
  chanceToUseGroundTilt: 1
  biome: AshLands
  minAltitude: 0.01
  maxAltitude: 40
  maxTerrainDelta: 2
  groupRadius: 32
- prefab: RockChunk_Ashlands_TW
  enabled: true
  min: 1
  max: 3
  scaleMin: 0.15
  scaleMax: 0.3
  randTilt: 20
  chanceToUseGroundTilt: 1
  biome: AshLands
  minAltitude: 0.01
  maxAltitude: 1000
  maxTerrainDelta: 4
  groundOffset: -1
  inForest: true
  forestTresholdMin: 0.5

- prefab: Pickable_VolcanicStone_TW
  enabled: true
  min: 3
  max: 3
  forcePlacement: true
  chanceToUseGroundTilt: 1
  biome: AshLands
  minAltitude: 0.1
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groupSizeMax: 3
  groupRadius: 5
- prefab: Pickable_GlacierStone_TW
  enabled: true
  min: 3
  max: 3
  forcePlacement: true
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.1
  maxAltitude: 1000
  maxTerrainDelta: 2
  groupSizeMax: 3
  groupRadius: 5
- prefab: MineRock_Tyranium_TW
  enabled: true
  min: 0.5
  max: 0.7
  scaleMax: 1.1
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.1
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -0.5
  inForest: true
  forestTresholdMin: 0.5
- prefab: MineRock_VolcanicFragment_TW
  enabled: true
  max: 0.4
  scaleMax: 1.1
  biome: AshLands
  minAltitude: 0.1
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -1
  inForest: true
  forestTresholdMin: 0.5
- prefab: Rock_Ashlands_TW
  enabled: true
  max: 10
  scaleMin: 0.9
  scaleMax: 1.1
  chanceToUseGroundTilt: 1
  biome: AshLands
  minAltitude: 0.01
  maxAltitude: 1000
  maxTerrainDelta: 4
- prefab: Boulder_DeepNorth_TW
  enabled: true
  max: 0.5
  scaleMin: 0.8
  scaleMax: 1.2
  randTilt: 10
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.01
  maxAltitude: 1000
  maxTerrainDelta: 2
  groundOffset: -2
- prefab: SmallRock_Ashlands_TW
  enabled: true
  max: 0.6
  scaleMin: 0.9
  scaleMax: 1.2
  chanceToUseGroundTilt: 1
  biome: AshLands
  minAltitude: 0.01
  maxAltitude: 1000
  maxTerrainDelta: 2
  groupSizeMax: 2
  groupRadius: 10
- prefab: MineRock_GlacierFragment_TW
  enabled: true
  max: 0.6
  scaleMax: 1.1
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.1
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -1
  inForest: true
  forestTresholdMin: 0.5
- prefab: BurnedTree_TW
  enabled: true
  min: 3
  max: 3
  scaleMin: 0.8
  scaleMax: 1.4
  randTilt: 4
  chanceToUseGroundTilt: 0.05
  biome: AshLands
  minAltitude: 5
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -1
  groupSizeMax: 3
  groupRadius: 32
  forestTresholdMin: 1.05
  forestTresholdMax: 1.3
- prefab: DeadBurnedTree_TW
  enabled: true
  min: 30
  max: 30
  scaleMin: 0.8
  scaleMax: 1.2
  randTilt: 4
  chanceToUseGroundTilt: 0.05
  biome: AshLands
  minAltitude: 5
  maxAltitude: 1000
  maxTilt: 30
  maxTerrainDelta: 2
  groundOffset: -1
  groupSizeMax: 3
  groupRadius: 32
  forestTresholdMin: 1.05
  forestTresholdMax: 1.3
- prefab: Stalag_DeepNorth_TW
  enabled: true
  max: 0.6
  scaleMax: 1.1
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.1
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -1
  inForest: true
  forestTresholdMin: 0.5
- prefab: BlackIce_DeepNorth_TW
  enabled: true
  max: 0.4
  scaleMax: 1.1
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.1
  maxAltitude: 45
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -0.5
  groupSizeMax: 2
  groupRadius: 32
  inForest: true
  forestTresholdMin: 0.5
- prefab: BorealTree_TW
  enabled: true
  min: 10
  max: 10
  scaleMin: 0.8
  scaleMax: 1.4
  randTilt: 4
  chanceToUseGroundTilt: 0.5
  biome: DeepNorth
  minAltitude: 5
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -1
  groupSizeMax: 5
  groupRadius: 32
  forestTresholdMin: 1.05
  forestTresholdMax: 1.3
- prefab: DeadBorealTree_TW
  enabled: true
  min: 32
  max: 36
  scaleMin: 0.8
  scaleMax: 1.2
  randTilt: 4
  chanceToUseGroundTilt: 0.5
  biome: DeepNorth
  minAltitude: 5
  maxAltitude: 1000
  maxTilt: 30
  maxTerrainDelta: 2
  groundOffset: -1
  groupSizeMax: 3
  groupRadius: 32
  forestTresholdMin: 1.05
  forestTresholdMax: 1.3
- prefab: Pickable_TundraBerryBush_TW
  enabled: true
  max: 0.8
  chanceToUseGroundTilt: 0.05
  biome: DeepNorth
  minAltitude: 10
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groupSizeMax: 2
  groupRadius: 32
- prefab: Pickable_PrimalLeak_TW
  enabled: true
  max: 0.65
  chanceToUseGroundTilt: 0.05
  biome: DeepNorth
  minAltitude: 10
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -0.2
  groupSizeMax: 2
  groupRadius: 16
- prefab: Pickable_AshenRoot_TW
  enabled: true
  max: 0.5
  biome: AshLands
  minAltitude: 10
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -0.25
  groupSizeMax: 2
  groupRadius: 16
- prefab: Pickable_FireLilly_TW
  enabled: true
  max: 0.5
  biome: AshLands
  minAltitude: 10
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groupSizeMax: 2
  groupRadius: 32
- prefab: DeadBorealPineTree_TW
  enabled: true
  min: 4
  max: 10
  scaleMin: 0.4
  scaleMax: 0.8
  randTilt: 4
  chanceToUseGroundTilt: 0.5
  biome: DeepNorth
  minAltitude: 5
  maxAltitude: 1000
  maxTilt: 8
  maxTerrainDelta: 2
  groundOffset: -1
  groupSizeMax: 3
  groupRadius: 32
  forestTresholdMin: 1.02
  forestTresholdMax: 1.6
- prefab: BorealPineTree_TW
  enabled: true
  min: 3
  max: 7
  scaleMin: 0.42
  scaleMax: 0.8
  randTilt: 4
  chanceToUseGroundTilt: 0.5
  biome: DeepNorth
  minAltitude: 5
  maxAltitude: 1000
  maxTilt: 8
  maxTerrainDelta: 2
  groundOffset: -1
  groupSizeMax: 3
  groupRadius: 32
  forestTresholdMin: 1.02
  forestTresholdMax: 1.6
- prefab: BorealPineTreeNormal_TW
  enabled: true
  min: 5
  max: 8
  scaleMin: 0.42
  scaleMax: 0.7
  randTilt: 4
  chanceToUseGroundTilt: 0.5
  biome: DeepNorth
  minAltitude: 5
  maxAltitude: 1000
  maxTilt: 8
  maxTerrainDelta: 2
  groundOffset: -1
  groupSizeMax: 3
  groupRadius: 32
  forestTresholdMin: 1.02
  forestTresholdMax: 1.6
- prefab: GswordAL_TW
  enabled: true
  max: 0.2
  scaleMin: 0.8
  scaleMax: 1.1
  biome: AshLands
  biomeArea: median
  minAltitude: 20
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 3
  forestTresholdMin: 0.5
- prefab: GswordDN_TW
  enabled: true
  max: 0.2
  scaleMin: 0.8
  scaleMax: 1.1
  biome: DeepNorth
  biomeArea: median
  minAltitude: 20
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 3
  groundOffset: 1
  inForest: true
  forestTresholdMin: 0.5
- prefab: Rock_DeepNorth_TW
  enabled: true
  max: 10
  scaleMax: 1.4
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.01
  maxAltitude: 1000
  maxTerrainDelta: 4
  groundOffset: -0.1
- prefab: RockPillar_Ashlands_TW
  enabled: true
  max: 0.25
  scaleMin: 0.8
  scaleMax: 1.3
  randTilt: 20
  chanceToUseGroundTilt: 0.05
  biome: AshLands
  minAltitude: -1
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -3
  inForest: true
  forestTresholdMin: 1
  forestTresholdMax: 1.2
- prefab: RockChunk_DeepNorth_TW
  enabled: true
  max: 0.5
  scaleMin: 0.8
  scaleMax: 1.1
  randTilt: 20
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.01
  maxAltitude: 1000
  maxTerrainDelta: 2
  groundOffset: -1
- prefab: Pickable_BranchBoreal_TW
  enabled: true
  max: 1
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.01
  maxAltitude: 1000
  maxTerrainDelta: 2
- prefab: BorealBush1_TW
  enabled: true
  min: 3
  max: 3
  forcePlacement: true
  scaleMin: 0.7
  scaleMax: 1.2
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.1
  maxAltitude: 1000
  maxTilt: 15
  maxTerrainDelta: 2
  groupSizeMax: 4
  groupRadius: 25
- prefab: BorealBush2_TW
  enabled: true
  min: 3
  max: 3
  forcePlacement: true
  scaleMin: 0.7
  scaleMax: 1.2
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.1
  maxAltitude: 1000
  maxTilt: 15
  maxTerrainDelta: 2
  groupSizeMax: 4
  groupRadius: 20
- prefab: BorealBush3_TW
  enabled: true
  min: 2
  max: 2
  forcePlacement: true
  scaleMin: 0.7
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.1
  maxAltitude: 1000
  maxTilt: 15
  maxTerrainDelta: 2
  groupRadius: 32
- prefab: Pickable_BranchScorched_TW
  enabled: true
  max: 1
  chanceToUseGroundTilt: 1
  biome: AshLands
  minAltitude: 0.01
  maxAltitude: 1000
  maxTerrainDelta: 2
  inForest: true
- prefab: Boulder_Ashlands_TW
  enabled: true
  max: 0.5
  scaleMin: 0.8
  scaleMax: 1.2
  randTilt: 10
  chanceToUseGroundTilt: 1
  biome: AshLands
  minAltitude: 0.01
  maxAltitude: 1000
  maxTerrainDelta: 2
  groundOffset: -2
- prefab: RockPillar_DeepNorth_TW
  enabled: true
  max: 0.3
  scaleMin: 0.8
  scaleMax: 1.3
  randTilt: 20
  chanceToUseGroundTilt: 0.05
  biome: DeepNorth
  minAltitude: -1
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -2.5
  forestTresholdMin: 1
  forestTresholdMax: 1.2
- prefab: Pickable_Mushroom_Wintercap_TW
  enabled: true
  max: 0.7
  randTilt: 10
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.01
  maxAltitude: 60
  maxTerrainDelta: 2
  groupRadius: 32
- prefab: AshenTree_TW
  enabled: true
  max: 0.4
  scaleMin: 0.8
  scaleMax: 1.2
  randTilt: 1
  biome: AshLands
  minAltitude: 5
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 3
  groundOffset: -0.5
  forestTresholdMin: 0.5
- prefab: Pickable_Mushroom_Flamecap_TW
  enabled: true
  max: 0.7
  randTilt: 5
  chanceToUseGroundTilt: 1
  biome: AshLands
  minAltitude: 0.01
  maxAltitude: 40
  maxTerrainDelta: 2
  groupRadius: 32
- prefab: RockChunk_Ashlands_TW
  enabled: true
  min: 1
  max: 3
  scaleMin: 0.15
  scaleMax: 0.3
  randTilt: 20
  chanceToUseGroundTilt: 1
  biome: AshLands
  minAltitude: 0.01
  maxAltitude: 1000
  maxTerrainDelta: 4
  groundOffset: -1
  inForest: true
  forestTresholdMin: 0.5
