name: Recipe_SaddleT5
clonePrefabName: NO
craftingStation: $piece_forge
minStationLevel: 3
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: true
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- LeatherScraps:10:0:False
- BlackBearPelt_TW:5:0:False
- GrizzlyBearPelt_TW:2:0:False
- Tar:5:0:False
