Temptwo:
  completed_achievements: 1
  total_kills: 0
  total_deaths: 0
Arnwald:
  completed_achievements: 1
  total_kills: 0
  total_deaths: 0
Pookwald:
  completed_achievements: 11
  total_kills: 1330
  total_deaths: 43
Sketaful Online:
  completed_achievements: 6
  total_kills: 735
  total_deaths: 13
ƑÆßþÐƒt:
  completed_achievements: 1
  total_kills: 152
  total_deaths: 4
KnAeG:
  completed_achievements: 1
  total_kills: 0
  total_deaths: 0
Sketaful Novia:
  completed_achievements: 2
  total_kills: 352
  total_deaths: 2
GrEmLiN:
  completed_achievements: 2
  total_kills: 0
  total_deaths: 1
