name: DeathKnightHelm_Recipe_Workbench
clonePrefabName: NO
craftingStation: ''
minStationLevel: 3
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- TrophyDeathsquito:2:0:True
- LinenThread:4:0:True
- LeatherScraps:4:0:True
