name: Recipe_FishingBaitOcean
clonePrefabName: NO
craftingStation: $piece_preptable
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 20
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- FishingBait:20:1:True
- TrophySerpent:1:1:True
