name: HelmetCircletSilver_Stamina_TW_Recipe_Custom
clonePrefabName: NO
craftingStation: $piece_arcaneanvil_TW
minStationLevel: 3
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- HelmetCircletSilver_TW:1:0:True
- Diamond_TW:1:1:True
- ShardModer_TW:4:2:True
- Crystal:8:2:True
- Silver:0:6:True
