name: EnchantedWoodSwamp_TW_Recipe_Custom
clonePrefabName: NO
craftingStation: $piece_arcaneanvil_TW
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 5
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- ElderBark:5:0:True
- Ooze:1:0:True
- ShardBonemass_TW:1:0:True
