name: DrakkarChili_TW_Recipe_Cauldron
clonePrefabName: NO
craftingStation: $piece_cauldron
minStationLevel: 5
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- MammothMeat_TW:1:0:True
- BurningFang_TW:1:0:True
- Helweed_TW:1:0:True
- PrimalLeak_TW:1:0:True
