name: DualSwordSkadi_TW_Recipe_Custom
clonePrefabName: NO
craftingStation: $piece_ymirforge_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- TyraniumBar_TW:30:15:True
- RuneRage_TW:20:10:True
- BlackIce_TW:30:15:True
- TrophyArcticGolem_TW:1:1:True
