name: SeedBag_Recipe_Workbench
clonePrefabName: NO
craftingStation: $piece_workbench
minStationLevel: 3
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- LeatherScraps:3:0:True
- DeerHide:1:0:True
- BlackBearPelt_TW:0:1:True
- RazorbackLeather_TW:0:1:True
- TrollHide:0:1:True
- GrizzlyBearPelt_TW:0:1:True
- RottenPelt_TW:0:1:True
- WolfPelt:0:1:True
- WolfHairBundle:0:1:True
- LinenThread:0:2:True
- LoxPelt:0:1:True
- Bilebag:0:2:True
- BlackCore:0:1:True
- AskHide:0:1:True
- MorgenSinew:0:1:True
