name: DualAxeDemonic_TW_Recipe_Forge
clonePrefabName: NO
craftingStation: $piece_forge
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Iron:30:15:True
- SurtlingCore:15:8:True
- Bloodbag:15:8:True
- TrophyDraugrElite:1:1:True
