name: BCA_Coated_VoltureEgg_Recipe_FoodPreparationTable
clonePrefabName: NO
craftingStation: $piece_preptable
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- VoltureEgg:1:0:True
- BCA_Salt:35:0:True
- BeechSeeds:10:0:True
