name: HelmetCircletBM_Sneak_TW_Recipe_Custom
clonePrefabName: NO
craftingStation: $piece_arcaneanvil_TW
minStationLevel: 3
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- HelmetCircletBM_TW:1:0:True
- Emerald_TW:1:1:True
- ShardYagluth_TW:5:2:True
- TrophyDeathsquito:1:0:True
- BlackMetal:0:7:True
