name: RuneWrath_TW_Recipe_Custom
clonePrefabName: NO
craftingStation: $piece_runesphere_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 10
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- RuneRage_TW:5:0:True
- RuneDestruction_TW:5:0:True
- FenrirArtifact_TW:5:0:True
