name: PotionRejuvenationMinor_TW_Recipe_Custom
clonePrefabName: NO
craftingStation: $piece_potioncauldron_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 3
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- ShardBonemass_TW:2:0:True
- MeadHealthMinor:2:0:True
- MeadStaminaMinor:2:0:True
- MeadEitrBlackForest_TW:2:0:True
