name: FabricBundle_Blackforest_TW_Recipe_Custom
clonePrefabName: NO
craftingStation: $piece_weavingloom_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 4
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- DeerHide:4:0:True
- Resin:6:0:True
- ShardElder_TW:2:0:True
