name: EnchantedWoodMountain_TW_Recipe_Custom
clonePrefabName: NO
craftingStation: $piece_arcaneanvil_TW
minStationLevel: 3
maxStationLevelCap: 
repairStation: 
amount: 5
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Wood:25:0:True
- FreezeGland:1:0:True
- ShardModer_TW:1:0:True
