name: MeatPieUncooked_TW_Recipe_PrepTable
clonePrefabName: NO
craftingStation: $piece_preptable
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 2
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- MammothMeat_TW:1:0:True
- ArcticBearSteak_TW:1:0:True
- PrimalLeak_TW:2:0:True
- Helweed_TW:3:0:True
