name: HelmetFenrirThoradus_TW_Recipe_Custom
clonePrefabName: NO
craftingStation: $piece_ymirforge_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- ThoradusBar_TW:18:9:True
- FurBundleNorth_TW:16:8:True
- RuneWrath_TW:8:6:True
- ArcticMammothTusk_TW:4:4:True
