name: ArcaneScroll_DamageBuff_TW_Recipe_Custom
clonePrefabName: NO
craftingStation: $piece_arcaneanvil_TW
minStationLevel: 4
maxStationLevelCap: 
repairStation: 
amount: 2
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- ArcaneScroll_Swamp_TW:1:0:True
- ArcaneScroll_Plains_TW:1:0:True
