name: HelmetCircletBM_TW_Recipe_Custom
clonePrefabName: NO
craftingStation: $piece_wizardtable_TW
minStationLevel: 6
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- BlackMetal:14:0:True
