name: BCA_Salt_Recipe_Custom
clonePrefabName: NO
craftingStation: $bca_crusher
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 5
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- BCA_SaltRock:1:0:True
