name: WarpikeElder_TW_Recipe_Forge
clonePrefabName: NO
craftingStation: $piece_forge
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- ElderBark:30:15:True
- Bronze:25:12:True
- AncientSeed:8:4:True
- TrophyTheElder:1:1:True
