name: ArrowNjord_TW_Recipe_Custom
clonePrefabName: NO
craftingStation: $piece_ymirforge_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 40
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- BorealWood_TW:6:0:True
- TyraniumBar_TW:1:0:True
- Feathers:2:0:True
