name: EnchantedWoodBlackForest_TW_Recipe_Custom
clonePrefabName: NO
craftingStation: $piece_arcaneanvil_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 5
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- RoundLog:5:0:True
- GreydwarfEye:2:0:True
- ShardElder_TW:1:0:True
