name: Recipe_el_T1Food
clonePrefabName: NO
craftingStation: $piece_cauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: $piece_cauldron
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- MeadTasty:1:1:True
- MushroomYellow:3:2:True
- LeatherScraps:1:1:True
