name: VolcanicBlade_TW_Recipe_Custom
clonePrefabName: NO
craftingStation: $piece_ymirforge_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- RagnoriteBar_TW:30:15:True
- RuneDestruction_TW:16:4:True
- SurtrIdol_TW:6:3:True
- TrophySurtrBrute_TW:1:1:True
