name: SledgeSurtr_TW_Recipe_Custom
clonePrefabName: NO
craftingStation: $piece_ymirforge_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- RagnoriteBar_TW:28:14:True
- RuneDestruction_TW:16:8:True
- BorealPineWood_TW:22:12:True
- TrophyArcticGolem_TW:1:1:True
