name: ShieldNjord_TW_Recipe_Custom
clonePrefabName: NO
craftingStation: $piece_ymirforge_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- TyraniumBar_TW:12:6:True
- FurBundleNorth_TW:10:5:True
- BorealWood_TW:12:6:True
- JotunnEye_TW:6:3:True
