name: RingPlains_TW_Recipe_Custom
clonePrefabName: NO
craftingStation: $piece_arcaneanvil_TW
minStationLevel: 4
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- ShardYagluth_TW:4:0:True
- BlackMetal:4:0:True
- Emerald_TW:1:1:True
- TrophyGrowth:1:0:True
