name: PotionAquatic_TW_Recipe_Custom
clonePrefabName: NO
craftingStation: $piece_potioncauldron_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 3
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- ShardModer_TW:2:0:True
- MushroomWizardbutter_TW:3:0:True
- FishRaw:6:0:True
- Chitin:2:0:True
