name: GreatbowModer_TW_Recipe_Custom
clonePrefabName: NO
craftingStation: $piece_fletchertable_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Silver:50:25:True
- Crystal:30:15:True
- FreezeGland:20:10:True
- TrophyDragonQueen:1:1:True
