Abomination: Undead
Bat: MountainMonsters
Blob: Undead
BlobElite: Undead
BlobTar: Undead
Boar: ForestMonsters
Boar_piggy: ForestMonsters
Bonemass: Boss
Chicken: ForestMonsters
Deathsquito: PlainsMonsters
Deer: ForestMonsters
Dragon: Boss
Draugr: Undead
Draugr_Elite: Undead
Draugr_Ranged: Undead
Dverger: Dverger
DvergerMage: Dverger
DvergerMageFire: Dverger
DvergerMageIce: Dverger
DvergerMageSupport: Dverger
DvergerTest: Dverger
Eikthyr: Boss
Fenring: MountainMonsters
Fenring_Cultist: MountainMonsters
Fenring_Cultist_Hildir: MountainMonsters
Fenring_Cultist_Hildir_nochest: MountainMonsters
gd_king: Boss
Ghost: Undead
Gjall: MistlandsMonsters
Goblin: PlainsMonsters
GoblinArcher: PlainsMonsters
GoblinBrute: PlainsMonsters
GoblinBruteBros: PlainsMonsters
GoblinBruteBros_nochest: PlainsMonsters
GoblinBrute_Hildir: PlainsMonsters
GoblinKing: Boss
GoblinShaman: PlainsMonsters
GoblinShaman_Hildir: PlainsMonsters
GoblinShaman_Hildir_nochest: PlainsMonsters
Greydwarf: ForestMonsters
Greydwarf_Elite: ForestMonsters
Greydwarf_Shaman: ForestMonsters
Greyling: ForestMonsters
Hare: AnimalsVeg
Hatchling: MountainMonsters
Hen: ForestMonsters
Hive: Boss
Leech: Undead
Leech_cave: Undead
Lox: PlainsMonsters
Lox_Calf: PlainsMonsters
Mistile: Dverger
Neck: ForestMonsters
Seeker: MistlandsMonsters
SeekerBrute: MistlandsMonsters
SeekerBrood: MistlandsMonsters
SeekerQueen: Boss
Serpent: SeaMonsters
Skeleton: Undead
Skeleton_Friendly: Players
Skeleton_Hildir: Undead
Skeleton_Hildir_nochest: Undead
Skeleton_NoArcher: Undead
Skeleton_Poison: Undead
StoneGolem: ForestMonsters
Surtling: Demon
TentaRoot: Boss
TheHive: MistlandsMonsters
Tick: MistlandsMonsters
Troll: ForestMonsters
TrainingDummy: Undead
Ulv: MountainMonsters
Wolf: MountainMonsters
Wolf_cub: MountainMonsters
Wraith: Undead