Mr Modtester:
  completed_achievements: 0
  total_kills: 71
  total_deaths: 10
ThySketis:
  completed_achievements: 15
  total_kills: 1659
  total_deaths: 12
Knaves:
  completed_achievements: 20
  total_kills: 3534
  total_deaths: 20
AceBlizzardz:
  completed_achievements: 0
  total_kills: 0
  total_deaths: 0
Viess:
  completed_achievements: 0
  total_kills: 0
  total_deaths: 0
Norsk:
  completed_achievements: 0
  total_kills: 0
  total_deaths: 0
Ganny:
  completed_achievements: 0
  total_kills: 103
  total_deaths: 4
Vyylette:
  completed_achievements: 0
  total_kills: 5
  total_deaths: 1
Lá Eless:
  completed_achievements: 0
  total_kills: 0
  total_deaths: 0
