name: Pickable_GrownMushroomWintercap_TW
itemPrefab: MushroomWintercap_TW
cloneOfWhatPickable: 
material: 
amount: 2
size: 
overrideName: ''
respawnTimer: 0
spawnOffset: 1
ifHasHealth: 50
hiddenChildWhenPicked: 
extraDrops: 
