name: BCA_Wild_Tomato
itemPrefab: BCA_Tomato
cloneOfWhatPickable: 
material: 
amount: 1
size: 
overrideName: $bca_wild_tomato
respawnTimer: 600
spawnOffset: 1
ifHasHealth: 30
hiddenChildWhenPicked: Tomatos
extraDrops:
  drops:
  - BCA_TomatoSeeds
  dropMin: 1
  dropMax: 1
  dropChance: 0.5
  dropOneOfEach: false
