name: Pickable_Fiddlehead
itemPrefab: Fiddleheadfern
cloneOfWhatPickable: 
material: 
amount: 3
size: 
overrideName: ''
respawnTimer: 300
spawnOffset: 0.5
ifHasHealth: 
hiddenChildWhenPicked: visual
extraDrops: 
