name: Pickable_SythrakSkelly_03_TW
itemPrefab: BoneFragments
cloneOfWhatPickable: 
material: 
amount: 1
size: 
overrideName: $item_pickable_skeletalremains
respawnTimer: 500
spawnOffset: 0.5
ifHasHealth: 
hiddenChildWhenPicked: crypt_skeleton_pile03
extraDrops: 
