name: Pickable_CaveDeepNorth_MeatPile_01
itemPrefab: MammothMeat_TW
cloneOfWhatPickable: 
material: 
amount: 1
size: 
overrideName: $item_pickable_meatpile
respawnTimer: 0
spawnOffset: 0.5
ifHasHealth: 
hiddenChildWhenPicked: meatpile
extraDrops:
  drops:
  - ArcticWolfMeat_TW
  - ArcticMammothTusk_TW
  dropMin: 1
  dropMax: 3
  dropChance: 1
  dropOneOfEach: false
