name: Pickable_DragonEgg
itemPrefab: DragonEgg
cloneOfWhatPickable: 
material: 
amount: 1
size: 
overrideName: ''
respawnTimer: 480
spawnOffset: 0.5
ifHasHealth: 
hiddenChildWhenPicked: visual
extraDrops: 
