name: VineGreen
itemPrefab: Vineberry
cloneOfWhatPickable: 
material: 
amount: 3
size: 
overrideName: ''
respawnTimer: 200
spawnOffset: 1
ifHasHealth: 
hiddenChildWhenPicked: Berries
extraDrops:
  drops:
  - VineGreenSeeds
  dropMin: 1
  dropMax: 3
  dropChance: 0.2
  dropOneOfEach: false
