name: Pickable_BranchBoreal_TW
itemPrefab: BorealWood_TW
cloneOfWhatPickable: 
material: 
amount: 1
size: 
overrideName: $deepnorth_branch_TW
respawnTimer: 1500
spawnOffset: 0.5
ifHasHealth: 
hiddenChildWhenPicked: model
extraDrops: 
