name: Pickable_Mushroom_Deathcap_TW
itemPrefab: MushroomDeathcap_TW
cloneOfWhatPickable: 
material: 
amount: 1
size: 
overrideName: ''
respawnTimer: 900
spawnOffset: 0.5
ifHasHealth: 
hiddenChildWhenPicked: Deathcap
extraDrops: 
