name: BFP_Pickable_Reed
itemPrefab: BFP_Straw
cloneOfWhatPickable: 
material: 
amount: 3
size: 
overrideName: $bfp_reed
respawnTimer: 240
spawnOffset: 0.5
ifHasHealth: 
hiddenChildWhenPicked: visual
extraDrops: 
