name: Pickable_MountainRemains01_buried
itemPrefab: BoneFragments
cloneOfWhatPickable: 
material: 
amount: 1
size: 
overrideName: $item_pickable_skeletalremains
respawnTimer: 0
spawnOffset: 0.5
ifHasHealth: 
hiddenChildWhenPicked: 
extraDrops:
  drops:
  - SilverNecklace
  dropMin: 1
  dropMax: 1
  dropChance: 0.506
  dropOneOfEach: false
