name: BlueberriesVegvisirAsmodeus
itemPrefab: Blueberries
cloneOfWhatPickable: 
material: 
amount: 1
size: 
overrideName: $item_blueberries
respawnTimer: 600
spawnOffset: 1
ifHasHealth: 
hiddenChildWhenPicked: BlueberriesVegvisirAsmodeus
extraDrops: 
