name: Pickable_Mushroom_Witcheye_TW
itemPrefab: MushroomWitcheye_TW
cloneOfWhatPickable: 
material: 
amount: 1
size: 
overrideName: ''
respawnTimer: 720
spawnOffset: 0.5
ifHasHealth: 
hiddenChildWhenPicked: WitchEyeShroom
extraDrops: 
