name: Pickable_ForestCryptRemains01
itemPrefab: BoneFragments
cloneOfWhatPickable: 
material: 
amount: 1
size: 
overrideName: $item_pickable_skeletalremains
respawnTimer: 0
spawnOffset: 0.5
ifHasHealth: 
hiddenChildWhenPicked: 
extraDrops: 
