name: Pickable_Mushroom
itemPrefab: Mushroom
cloneOfWhatPickable: 
material: 
amount: 1
size: 
overrideName: ''
respawnTimer: 240
spawnOffset: 0.5
ifHasHealth: 
hiddenChildWhenPicked: visual
extraDrops: 
