name: Pickable_ChainedMeat_TW
itemPrefab: ArcticWolfMeat_TW
cloneOfWhatPickable: 
material: 
amount: 1
size: 
overrideName: $pickable_chainedmeat_TW
respawnTimer: 1500
spawnOffset: 0.5
ifHasHealth: 
hiddenChildWhenPicked: Carcass
extraDrops: 
