name: Pickable_GrownMushroomWitcheye_TW
itemPrefab: MushroomWitcheye_TW
cloneOfWhatPickable: 
material: 
amount: 2
size: 
overrideName: ''
respawnTimer: 0
spawnOffset: 1
ifHasHealth: 15
hiddenChildWhenPicked: 
extraDrops: 
